services:
  - type: web
    name: lehydrosy-python
    env: python
    plan: free
    rootDir: python_server
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server:app"
